logging:
  config: classpath:logback-spring-local.xml

spring:
  kafka:
    bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
      port: 9988
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: local-secret-key-with-40-symbols-1234567
  datasource:
    url: jdbc:postgresql://localhost:5432/to-do-app-db
    username: postgres
    password: password2

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true